### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Panderium** [PolytechLyon/isi3-test-fougerouse-tests#1]
Bonjour @Slashgear,
Pouvez-vous me faire un retour sur mon travail ?
Merci

**Comment by Slashgear** [comment]
>Si on a la volonté de faire des tests unitaires, cette situation est-elle normale ? Pourquoi ?
On *ne peut pas faire de tests unitaires sur la classe Person* car les tests dépendaient de la classe Vector.

Ici le tests n'était pas unitaire mais c'est possible d'en faire. On l'a fait.

Faux, cela souligne que tu ne semble pas trop avoir compris ce qu'étaient des tests unitaires. Pourrais tu essayer dans donner une définition simple ici ?

**Comment by Slashgear** [comment]
Ok ça me suffit
